### ISSUE TITLE
Do tools like autoprefixer work with free style?

### ISSUE THREAD

**Issue by Maximilianos** [blakeembrey/react-free-style#11]
autoprefixer is pretty baller with its handling of browser inconsistencies, how do you solve that in free-style land? thanks :)

**Comment by blakeembrey** [comment]
I made a comment on that here: https://github.com/blakeembrey/free-style/issues/10#issuecomment-165538698. It's actually quite simple to do and usually only a few lines of code.

**Comment by Maximilianos** [comment]
Okay, thanks. https://github.com/namuol/prefix-lite looks like the easiest to pick up and use, will give a spin.
