### ISSUE TITLE
typings for stateless components

### ISSUE THREAD

**Issue by agrady42** [blakeembrey/react-free-style#15]
I'm using typescript and I'd like to do something like this:

`const test = Style.component(() => <div></div>);`

but it's complaining "Argument of type () => Element is not assignable to parameter of type 'ComponentClass<any>'.

I think the only thing it needs is an overload of the component definition like this:

`component(Component: React.StatelessComponent<any> ): React.ComponentClass<any>;`

in the type definitions. Does that make sense? Should I make a pull request?

**Comment by blakeembrey** [comment]
Sounds great, would accept a PR. Could even just switch to `any` to avoid messing with React types that may change.

**Comment by agrady42** [comment]
I think I prefer the actual type - I don't foresee this changing a bunch more, and I don't mind coming back and fixing it again if I need:)

Incidentally this is my first pull request on a public project, and I'm usually more of a .NET guy, so please let me know if I did anything wrong.

**Comment by blakeembrey** [comment]
Released: https://github.com/blakeembrey/react-free-style/releases/tag/v2.2.1
