### ISSUE TITLE
Use component.displayName or Function.name

### ISSUE THREAD

**Issue by sladiri** [blakeembrey/react-free-style#26]
Wrapping a function seems returns an anonymous function currently. Therefore debuggers show as the component name.
```javascript
// has no name
const component = wrap(function Foo (props) {...}, Style);
```
As a workaround, I manually set the name to the returned function, but would it be possible to have `wrap` pickup the `displayName` of a Component or the `name` of a function automatically?
```javascript
// workaround to show name 'Foo'
const temp = wrap((props) => {...}, Style);
const component = Object.defineProperty(temp, "name", { value: "Foo" });
```

**Comment by blakeembrey** [comment]
It shouldn't be anonymous, but it's name is terrible today. Are you seeing `anonymous` or `Style`? Either way, I'd love to fix this and get some tests in to ensure it doesn't regress.

**Comment by blakeembrey** [comment]
Actually, you're right - derp. The function itself would have no name. Can we use the `displayName` technique here? I'll make a PR, can you let me know if it works for you?

**Comment by blakeembrey** [comment]
Would you like to test https://github.com/blakeembrey/react-free-style/pull/27 and let me know how it goes? Is there anywhere else that you feel helpful display names are missing?

**Comment by sladiri** [comment]
Thanks, the PR works fine for me, it picks up a function name (I am just using functions, no React components). Specifically, I am using the Cerebral.js framework and its Debugger tool ([link](http://cerebraljs.com/docs/introduction/debugger.html)).

**Comment by blakeembrey** [comment]
Great, I'll merge it today. I'll also expose a util function for the "style sheet" pattern that you can use since I just introduced a HOC as the main way to use `react-free-style` (everything else still works, but I found the current style more verbose in React than I wanted).
