### ISSUE TITLE
Optionally override styles passed in from parent

### ISSUE THREAD

**Issue by sladiri** [blakeembrey/react-free-style#30]
I tried out your example (https://github.com/blakeembrey/react-free-style/issues/29#issuecomment-315504972), and maybe it would be a feature to automatically override passed in styles to the child component.

This would allow me to define a component which is already wrapped inside its `withStyle`, so it would have its styles by default.
But if a parent passed in styles, it would be automatically picked up. Currently I would have to do this merging manually inside the child.

Would this be possible? I think `styled` should be modified (https://github.com/blakeembrey/react-free-style/blob/master/src/react-free-style.ts#L278) to check if props contain a styles object already.

Here is an example:
```js
// Child component:
export const styles = { button: { color: 'red' } };
const withStyle = styled(styles);
export const component = withStyle(props => <div className={props.styles.button} />);

// Parent component
// Optionally modify child styles
import { styles as childStyles, component as ChildComponent } from '.';
const withStyle = styled();
const styles = registerStyleSheet(withStyle.Style, ExternalComponent.styles)

// if styles is not passed to child, child should use its own.
const MyComponent = withStyle(props => <ChildComponent styles={styles} />);
```

**Comment by blakeembrey** [comment]
I'd suggest not using the HOC at all in this case. Assuming I understand correctly, I'd just go the other way and use `const styles = props.styles || myStyles` inside the component to suggest a default. I haven't really run into a case where having a parent prop override the HOC prop would be useful as it'd break a number of contract expectations. You can use the imperative `wrap` function instead (https://github.com/blakeembrey/react-free-style/blob/aa03a9a9b16dd88e7635fe8f2088ab56f3cc30a0/src/react-free-style.ts#L216) - the second argument takes a `Style` object (this is basically how the HOC works internally also). Let me know if that makes sense.

**Comment by sladiri** [comment]
OK, thank you for the explanation. I have little experience with CSS structure, but overriding is not a must for me either. I can pass classNames, which have been registered by the parent, for example.

**Comment by blakeembrey** [comment]
Happy to put something together for you as a demo, what do you think? I can add it to the README. We can also make it so it does `const styles = Object.assign({}, props.styles, myStyles)` so you'd end up with a hash of user-passed in styles combined with your own styles.

**Comment by sladiri** [comment]
An example for the Readme would be great, sure. :) After playing with it, it makes sense, in particular the HOC Readme part, It did take me some time to understand the main concept. At least I think I understood you and here is what I ended up. It seems pretty simple in hindsight, but as a beginner I did not see the forest for the trees, I guess. :)

- Import the same global Styles HOC for each component to wrap in. 
- There I can register local styles, if needed, and 

use them in addition to the styles from props.

Btw. I imported Tachyons.css manually, and it seems to work very well. There is some manual stuff to do it, but it is a nice start.

**Comment by blakeembrey** [comment]
@sladiri Let me know if https://github.com/blakeembrey/react-free-style/pull/31 is of any help! For `free-style`, you can definitely just combine global css class names with `free-style`-generated class names.

**Comment by sladiri** [comment]
That gives a nice example, yes. Now I see that I probably do not take advantage of the minimal CSS via register-stylesheet. I registered all classes of the CSS framework at once, so they would be present in the styles object, but this means that even unused classes would be injected into the <styles> tag. I hoped that react-free-style could track the used classes (`className={...}`) inside my components, and only inject used classes:

```js
// Global classes, not a CSS file
// styles.js
export default styled({/* styles */});
```
```js
// Component.js
import withStyle from "../styles";
const styles = registerStyleSheet(withStyle.Style, {/* styles */})
export default withStyle(props =>
  <div className={classNames(styles.foo, props.styles.bar)}>test</div>
);
```

**Comment by blakeembrey** [comment]
Right, I see. No, it's only tracking styles used at the file level. The common behaviour is to build one component per file, so excluding "unused" is at the component-level. I can try and clarify that also. `free-style` doesn't really manipulate anything outside of itself (e.g. `styles.css`) or check which class names are actually used. I'm not sure if checking class names is possible since it's usually an expression, which means parsing and checking at runtime - probably not the best time to be manipulating a stylesheet (fun fact: previous `free-style` versions used a `<Style />` React element where this would be impossible - can't render two things in the same tick).

I'm not so sure it's bad to register all those styles one. Especially since the user can pick and chose keys themselves if they wanted to cut down on size: `styled({ button: framework.button })`. Let me know what issues you see, hopefully we can make it work for you.

**Comment by sladiri** [comment]
OK, thank you again for the explanation. I will open another ticket for a question again. :)

**Comment by blakeembrey** [comment]
This is supported in `v5`! I simplified some of the API and examples, and this is one of the features I made sure to get working. If you don't want this and you're using the `styled()` HOC, use the `styled().styles` object instead of `props.styles`.
