### ISSUE TITLE
Wrapping with `Style.component( ... )` masks public methods

### ISSUE THREAD

**Issue by namuol** [blakeembrey/react-free-style#8]
If you wrap a component class with `Style.component( ... )`, you lose access to the unwrapped component-class's methods, which are [useful when utilizing `this.refs`](https://facebook.github.io/react/tips/expose-component-functions.html).

A contrived example:

```js
class FancyInput extends React.Component {
  focus () {
    this.refs.inputField.getDOMNode().focus();
  }

  render () {
    return (
      <input ref="inputField" />
    );
  }
}

FancyInput = Style.component(FancyInput);

class FancyForm extends React.Component {
  render () {
    return (
      <form onClick={() => {
        e.preventDefault();

        // "focus" is undefined, since we're not referring to
        //  the original FancyInput instance:
        this.refs.firstName.focus();
      }}>
        <FancyInput ref="firstName" />
        <FancyInput ref="lastName" />
      </form>
    );
  }
}

FancyForm = Style.component(FancyForm);
```

I can't think of any workarounds that don't change the original components' API. You *can* simply not wrap components, but you of course lose the benefits of doing so in the process.

Might it be possible for `ReactFreeStyle::component(...)` to return a new component class that *inherits* from the original component instead of wrapping it?

**Comment by blakeembrey** [comment]
Great point and some interesting ideas. I think the inheriting makes sense. I was originally thinking about just tweaking the methods and wrapping each function, but inheriting sounds nicer and I won't be mutating any properties. I'll have to looking into it a tiny bit more, but potentially the same pattern could be used as a decorator too, which might be cool to try out. I'll investigate some more, but it looks like the API can probably stay the same.

The other option would be to additionally provide a mixin for use.

**Comment by blakeembrey** [comment]
@namuol Would you be able to try out https://github.com/blakeembrey/react-free-style/tree/component-inheritance (you'll need to build the source locally). I managed to refactor it into a class (needed to use latest master for TypeScript) and took a while to discover the hot reloading issue - but it should all be there now.

**Comment by namuol** [comment]
Made some small bugfixes but it worked as hypothesized! I'll send over a PR shortly~ :beers:

**Comment by blakeembrey** [comment]
@namuol I made some more changes. Could you make one last review and we can look at putting it in `0.6`? One thing I am a little worried about is debugging. My React panel is broken and I haven't had time to test it yet, but I think the component names are going to break now since it's a `ReactFreeStyleComponent` class. Can you check and see whether (or I can in the next couple of days) it is broken, and whether we can just set the `ReactFreeStyleComponent.displayName = Component.displayName || Component.name`?

**Comment by namuol** [comment]
Yup -- adding that line indeed fixed debugger names. :)

---

By the way, I was having React Devtools problems too, and it turned out to be caused by WebPack loading `react` twice because it appeared twice in my node-module hierarchy, since I was using `npm link` on a live repo of `react-free-style`.

A [workaround](http://stackoverflow.com/questions/31169760/how-to-avoid-react-loading-twice-with-webpack-when-developing) was to force WebPack to only use the topmost in the hierarchy by including something like this in my webpack config:

```js
resolve: {
  alias: {
    react: path.resolve('./node_modules/react'),
  },
},
```
